# permissions for end users to edit novaconductors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novaconductor-editor-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - novaconductors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novaconductors/status
  verbs:
  - get
