# permissions for end users to view novaconductors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novaconductor-viewer-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - novaconductors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novaconductors/status
  verbs:
  - get
