# permissions for end users to edit novaschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novascheduler-editor-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - novaschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novaschedulers/status
  verbs:
  - get
