# permissions for end users to edit novametadata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novametadata-editor-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - novametadata
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novametadata/status
  verbs:
  - get
