# permissions for end users to view novaschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novascheduler-viewer-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - novaschedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novaschedulers/status
  verbs:
  - get
