# permissions for end users to view novanovncproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novanovncproxy-viewer-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - novanovncproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novanovncproxies/status
  verbs:
  - get
