# permissions for end users to view novametadata.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: novametadata-viewer-role
rules:
- apiGroups:
  - nova.openstack.org
  resources:
  - novametadata
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nova.openstack.org
  resources:
  - novametadata/status
  verbs:
  - get
