apiVersion: nova.openstack.org/v1beta1
kind: NovaMetadata
metadata:
  name: novacell1-novametadata
  namespace: openstack
spec:
  cell: cell1
  containerImage: docker.io/tripleomaster/centos-binary-nova-api:current-tripleo
  databaseHostname: mariadb
  managingCrName: novacell1
  neutronSecret: neutron-secret
  novaSecret: nova-secret
  placementSecret: placement-secret
  replicas: 1
  transportURLSecret: rabbitmq-transport-url-cell1
